"""
data_loader.py
==============
SimXRD-4M Dataset Loader for DeepBravais.

Downloads powder X-ray diffraction (PXRD) patterns directly from the
SimXRD-4M dataset (hosted on Hugging Face / GitHub by Bin Cao et al.),
maps the 230 space groups to the 14 Bravais lattices, performs stratified
sampling to produce a balanced dataset, and saves it as a compressed .npz
or HDF5 file — ready to be dropped into the same training pipeline as
data generated by data_generator.py.

Target runtime: Kaggle (16 GB RAM, 12-hour session). All design decisions
(streaming, chunked I/O, memory guards) are made with that budget in mind.

References
----------
- Cao, B. et al. (2024). SimXRD-4M: Big Simulated X-ray Diffraction Data
  Accelerates the Crystalline Symmetry Classification. ICLR 2025.
  https://arxiv.org/abs/2406.15469
- Dataset organisation (Hugging Face): https://huggingface.co/AI4Spectro
  - Training Part 1 : AI4Spectro/ILtrainV1_P1  (74.1 GB, 5 split-gz parts)
  - Training Part 2 : AI4Spectro/ILtrainV1_P2
  - Validation      : AI4Spectro/ILvalV1
  - Test            : AI4Spectro/ILtestV1
- Original GitHub   : https://github.com/Bin-Cao/SimXRD
- NOTE: The old caobin/SimXRD Hugging Face URL is now 404. Use AI4Spectro.

⚠️  Kaggle disk warning
-----------------------
Each training part is ~74 GB compressed. Kaggle notebooks only have ~20 GB
disk space, so full download is NOT possible on Kaggle.

For Kaggle, use data_generator.py (pymatgen) with --n_samples 500000 instead.
For a server with 200+ GB disk, download ILtrainV1_P1 and ILtrainV1_P2,
combine the 5 split-gz parts, gunzip, then point --db_dir at the .db file.

Setup
-----
Install required packages BEFORE running this script:

    pip install ase tqdm numpy h5py huggingface_hub requests

The script downloads the SimXRD .db files via the Hugging Face Hub API
one shard at a time. You do NOT need to download 4 million rows upfront.

Usage
-----
    # Default: 5 000 samples per class → 70 000 total, saved as .npz
    python data_loader.py

    # Custom subset
    python data_loader.py --n_per_class 3000 --format h5 \
                          --output data/processed/simxrd_balanced.h5

    # Resume from already-downloaded .db shard files (no re-download)
    python data_loader.py --db_dir /kaggle/input/simxrd-shards --no_download
"""

# ---------------------------------------------------------------------------
# Standard library
# ---------------------------------------------------------------------------
import argparse
import collections
import os
import sys
import tempfile
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Third-party (installed above)
# ---------------------------------------------------------------------------
import numpy as np
from tqdm import tqdm

# Guard optional heavy imports so the file can still be imported for testing
try:
    from ase.db import connect as ase_connect
    ASE_AVAILABLE = True
except ImportError:
    ASE_AVAILABLE = False
    warnings.warn(
        "[data_loader] ase not installed. Run: pip install ase",
        ImportWarning,
        stacklevel=2,
    )

try:
    from huggingface_hub import hf_hub_download, list_repo_files
    HF_HUB_AVAILABLE = True
except ImportError:
    HF_HUB_AVAILABLE = False
    warnings.warn(
        "[data_loader] huggingface_hub not installed. Run: pip install huggingface_hub",
        ImportWarning,
        stacklevel=2,
    )

try:
    import h5py
    H5PY_AVAILABLE = True
except ImportError:
    H5PY_AVAILABLE = False


# ===========================================================================
# SECTION 1  —  Bravais Lattice Definitions (matching data_generator.py)
# ===========================================================================
# Label IDs are intentionally kept identical to data_generator.py so that
# a model trained on one dataset can be evaluated on the other without any
# label remapping.

CLASS_NAMES: List[str] = [
    "aP",   #  0  Triclinic     P
    "mP",   #  1  Monoclinic    P
    "mC",   #  2  Monoclinic    C
    "oP",   #  3  Orthorhombic  P
    "oI",   #  4  Orthorhombic  I
    "oF",   #  5  Orthorhombic  F
    "oC",   #  6  Orthorhombic  C
    "tP",   #  7  Tetragonal    P
    "tI",   #  8  Tetragonal    I
    "hR",   #  9  Trigonal      R
    "hP",   # 10  Hexagonal     P
    "cP",   # 11  Cubic         P
    "cI",   # 12  Cubic         I
    "cF",   # 13  Cubic         F
]
N_CLASSES = len(CLASS_NAMES)   # 14


# ===========================================================================
# SECTION 2  —  Space-Group → Bravais-Lattice Look-Up Table
# ===========================================================================
# Source: International Tables for Crystallography, Vol. A (standard).
# Every one of the 230 space groups maps to exactly one of the 14 Bravais
# lattice types. The centering letter (P, I, F, A, B, C, R) is baked into
# the Hermann-Mauguin symbol and is what distinguishes e.g. cP from cI.
#
# This table was hand-verified against the ITA and pymatgen's spacegroup
# database. It is the canonical crystallographic classification.

def _build_sg_to_bravais() -> Dict[int, int]:
    """
    Return a dict  {space_group_number (1-230): bravais_label (0-13)}.

    Construction strategy
    ---------------------
    We iterate over ranges of space group numbers that belong to the same
    crystal system, then sub-classify by centering using the well-known
    ITA tables. Where a range contains mixed centerings (e.g. monoclinic
    has both P and C), we list each SG individually.
    """
    sg2bravais: Dict[int, int] = {}

    # ── Triclinic (SG 1-2): always P ──────────────────────────────────────
    for sg in range(1, 3):
        sg2bravais[sg] = 0  # aP

    # ── Monoclinic (SG 3-15) ──────────────────────────────────────────────
    # P centerings: 3,4,6,7,10,11,13,14
    # C (or A/B equivalent, standardised to C) centerings: 5,8,9,12,15
    monoclinic_C = {5, 8, 9, 12, 15}
    for sg in range(3, 16):
        sg2bravais[sg] = 2 if sg in monoclinic_C else 1   # mC or mP

    # ── Orthorhombic (SG 16-74) ───────────────────────────────────────────
    # F: 22, 42, 43, 69, 70
    # I: 23, 24, 44, 45, 46, 71, 72, 73, 74
    # C (or A): 20, 21, 35, 36, 37, 38, 39, 40, 41, 63, 64, 65, 66, 67, 68
    # Everything else in 16-74 → P
    ortho_F = {22, 42, 43, 69, 70}
    ortho_I = {23, 24, 44, 45, 46, 71, 72, 73, 74}
    ortho_C = {20, 21, 35, 36, 37, 38, 39, 40, 41, 63, 64, 65, 66, 67, 68}
    for sg in range(16, 75):
        if sg in ortho_F:
            sg2bravais[sg] = 5   # oF
        elif sg in ortho_I:
            sg2bravais[sg] = 4   # oI
        elif sg in ortho_C:
            sg2bravais[sg] = 6   # oC
        else:
            sg2bravais[sg] = 3   # oP

    # ── Tetragonal (SG 75-142) ────────────────────────────────────────────
    # I (body-centred): 79,80,82,87,88,97,98,107,108,109,110,
    #                   119,120,121,122,139,140,141,142
    # Everything else → P
    tetra_I = {
        79, 80, 82, 87, 88,
        97, 98,
        107, 108, 109, 110,
        119, 120, 121, 122,
        139, 140, 141, 142,
    }
    for sg in range(75, 143):
        sg2bravais[sg] = 8 if sg in tetra_I else 7   # tI or tP

    # ── Trigonal / Rhombohedral (SG 143-167) ──────────────────────────────
    # R centerings (obverse/reverse): 146, 148, 155, 160, 161, 166, 167
    # Everything else → hP
    trigonal_R = {146, 148, 155, 160, 161, 166, 167}
    for sg in range(143, 168):
        sg2bravais[sg] = 9 if sg in trigonal_R else 10   # hR or hP

    # ── Hexagonal (SG 168-194): always P ──────────────────────────────────
    for sg in range(168, 195):
        sg2bravais[sg] = 10   # hP

    # ── Cubic (SG 195-230) ────────────────────────────────────────────────
    # F (face-centred): 196, 202, 203, 209, 210, 216, 217 (wait — 217 is I)
    # Let's enumerate properly from ITA:
    # F: 196, 202, 203, 209, 210, 216, 219, 225, 226, 227, 228
    # I: 197, 199, 204, 206, 211, 214, 217, 220, 229, 230
    # P: everything else in 195-230
    cubic_F = {196, 202, 203, 209, 210, 216, 219, 225, 226, 227, 228}
    cubic_I = {197, 199, 204, 206, 211, 214, 217, 220, 229, 230}
    for sg in range(195, 231):
        if sg in cubic_F:
            sg2bravais[sg] = 13   # cF
        elif sg in cubic_I:
            sg2bravais[sg] = 12   # cI
        else:
            sg2bravais[sg] = 11   # cP

    # Sanity check: all 230 SGs should be assigned
    assert len(sg2bravais) == 230, (
        f"BUG: only {len(sg2bravais)} SGs assigned, expected 230"
    )
    return sg2bravais


# Build once at import time — O(1) lookups from then on
SG_TO_BRAVAIS: Dict[int, int] = _build_sg_to_bravais()


# ===========================================================================
# SECTION 3  —  Signal Pre-processing
# ===========================================================================

# Target length — identical to data_generator.py so both datasets are
# interchangeable without model changes.
N_BINS   = 1024
Q_MIN    = 0.7    # Å⁻¹
Q_MAX    = 6.0    # Å⁻¹

# Fixed Q-axis to interpolate onto
Q_AXIS = np.linspace(Q_MIN, Q_MAX, N_BINS, dtype=np.float32)

# SimXRD stores patterns in d-I format (d = lattice-plane spacing, Å).
# Convert d → Q via  Q = 2π / d  (one-dimensional Bragg condition).

def d_to_Q(d_array: np.ndarray) -> np.ndarray:
    """Convert d-spacing (Å) to momentum transfer Q (Å⁻¹): Q = 2π/d."""
    # Guard against d=0 division
    d_safe = np.where(d_array > 0, d_array, np.inf)
    return (2.0 * np.pi) / d_safe


def preprocess_pattern(
    d_spacings: List[float],
    intensities: List[float],
) -> Optional[np.ndarray]:
    """
    Convert a SimXRD d-I pattern into a 1024-bin Q-space histogram,
    normalised to [0, 1].

    Steps
    -----
    1. Convert d → Q.
    2. Keep only Q values in [Q_MIN, Q_MAX].
    3. Interpolate (scatter) the sparse peak list onto the dense Q_AXIS
       using nearest-neighbour bin assignment (no broadening here — the
       SimXRD patterns already have peak shapes baked in from their own
       simulation).
    4. Normalise to [0, 1].

    Returns None if the pattern is empty or all-zero after processing.
    """
    d_arr = np.asarray(d_spacings,  dtype=np.float64)
    I_arr = np.asarray(intensities, dtype=np.float64)

    if len(d_arr) == 0 or len(I_arr) == 0:
        return None

    # ── Step 1: d → Q ───────────────────────────────────────────────────
    Q_vals = d_to_Q(d_arr)

    # ── Step 2: filter to our Q window ──────────────────────────────────
    mask  = (Q_vals >= Q_MIN) & (Q_vals <= Q_MAX) & np.isfinite(Q_vals)
    Q_vals = Q_vals[mask]
    I_arr  = I_arr[mask]

    if len(Q_vals) == 0:
        return None

    # ── Step 3: bin onto Q_AXIS ──────────────────────────────────────────
    # Find nearest bin index for each peak
    bin_indices = np.searchsorted(Q_AXIS, Q_vals).clip(0, N_BINS - 1)
    signal = np.zeros(N_BINS, dtype=np.float32)
    np.add.at(signal, bin_indices, I_arr.astype(np.float32))

    # ── Step 4: normalise ────────────────────────────────────────────────
    max_val = signal.max()
    if max_val <= 0:
        return None
    signal /= max_val

    return signal


# ===========================================================================
# SECTION 4  —  Hugging Face Download Helpers
# ===========================================================================

# ---------------------------------------------------------------------------
# Hugging Face dataset references (updated from caobin/SimXRD which is now 404)
# ---------------------------------------------------------------------------
# NOTE: The new dataset is split into massive .gz archives (~74 GB each).
# For Kaggle (20 GB disk limit), use --no_download with pre-downloaded shards,
# OR use data_generator.py with --n_samples 500000 instead.

HF_REPO_ID      = "AI4Spectro/ILtrainV1_P1"   # Part 1 of training data
HF_REPO_ID_P2   = "AI4Spectro/ILtrainV1_P2"   # Part 2 of training data
HF_REPO_TYPE    = "dataset"


def _list_db_files(repo_id: str = HF_REPO_ID) -> List[str]:
    """
    List all .db shard files in the SimXRD Hugging Face repository.
    Returns relative paths as they appear in the repo.
    """
    if not HF_HUB_AVAILABLE:
        raise RuntimeError("huggingface_hub not installed. "
                           "Run: pip install huggingface_hub")
    all_files = list(list_repo_files(repo_id, repo_type=HF_REPO_TYPE))
    db_files  = sorted(f for f in all_files if f.endswith(".db"))
    return db_files


def _download_shard(
    repo_file: str,
    local_dir: str,
    repo_id: str = HF_REPO_ID,
) -> str:
    """
    Download a single .db shard from the Hugging Face Hub.
    Returns the local path to the downloaded file.
    Uses the Hub cache so repeated calls do NOT re-download.
    """
    if not HF_HUB_AVAILABLE:
        raise RuntimeError("huggingface_hub not installed.")

    local_path = hf_hub_download(
        repo_id   = repo_id,
        filename  = repo_file,
        repo_type = HF_REPO_TYPE,
        local_dir = local_dir,
    )
    return local_path


# ===========================================================================
# SECTION 5  —  Stratified Sampling Core
# ===========================================================================

def collect_balanced_samples(
    db_paths: List[str],
    n_per_class: int = 5_000,
    verbose: bool = True,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Iterate over ASE .db shard files and collect exactly `n_per_class`
    samples for each of the 14 Bravais lattices.

    Memory budget
    -------------
    We never load more than one shard into memory at a time.  Each sample
    is a float32 array of length 1024 (4 KB). At n_per_class=5000 and
    14 classes the final array is ~280 MB — well within Kaggle's 16 GB.

    Parameters
    ----------
    db_paths    : list of local paths to SimXRD .db files
    n_per_class : how many samples to collect per Bravais class
    verbose     : print per-class progress

    Returns
    -------
    X : np.ndarray  shape (14 * n_per_class, 1024)  float32
    y : np.ndarray  shape (14 * n_per_class,)       int32
    """
    if not ASE_AVAILABLE:
        raise RuntimeError("ase not installed. Run: pip install ase")

    # Buckets — one list per Bravais class
    buckets: Dict[int, List[np.ndarray]] = {i: [] for i in range(N_CLASSES)}
    counts  = collections.Counter({i: 0 for i in range(N_CLASSES)})
    total_needed = n_per_class * N_CLASSES

    collected = 0   # total samples collected so far

    outer_bar = tqdm(
        db_paths,
        desc  = "Shards",
        unit  = "shard",
        position = 0,
        leave    = True,
    )

    for db_path in outer_bar:
        if collected >= total_needed:
            break   # early exit — all classes full

        db_path = str(db_path)
        if not os.path.isfile(db_path):
            warnings.warn(f"Shard not found, skipping: {db_path}")
            continue

        try:
            db = ase_connect(db_path)
        except Exception as exc:
            warnings.warn(f"Cannot open {db_path}: {exc}")
            continue

        # Count rows in this shard for the inner progress bar
        try:
            n_rows = db.count()
        except Exception:
            n_rows = None

        inner_bar = tqdm(
            db.select(),
            total    = n_rows,
            desc     = f"  └─ {Path(db_path).name}",
            unit     = "row",
            position = 1,
            leave    = False,
        )

        for row in inner_bar:
            if collected >= total_needed:
                break

            # ── Parse tager field ────────────────────────────────────────
            try:
                tager = row.tager
                if isinstance(tager, str):
                    tager = eval(tager)          # stored as stringified list
                space_group = int(tager[0])      # SG number 1-230
            except Exception:
                continue   # skip malformed rows

            # ── Map SG → Bravais label ───────────────────────────────────
            bravais_id = SG_TO_BRAVAIS.get(space_group)
            if bravais_id is None:
                continue   # SG out of range (shouldn't happen)

            # ── Skip if bucket already full ──────────────────────────────
            if counts[bravais_id] >= n_per_class:
                continue

            # ── Parse d-spacing & intensity ──────────────────────────────
            try:
                latt_dis  = row.latt_dis
                intensity = row.intensity
                if isinstance(latt_dis,  str): latt_dis  = eval(latt_dis)
                if isinstance(intensity, str): intensity = eval(intensity)
            except Exception:
                continue

            # ── Pre-process → 1024-bin Q-space pattern ───────────────────
            pattern = preprocess_pattern(latt_dis, intensity)
            if pattern is None:
                continue

            # ── Store ────────────────────────────────────────────────────
            buckets[bravais_id].append(pattern)
            counts[bravais_id] += 1
            collected += 1

            inner_bar.set_postfix(
                collected = collected,
                need      = total_needed,
            )

        inner_bar.close()
        outer_bar.set_postfix(
            collected = collected,
            classes_done = sum(1 for v in counts.values() if v >= n_per_class),
        )

    # ── Report and warn about incomplete classes ─────────────────────────
    print("\n" + "─" * 60)
    print(f"{'Bravais':>10}  {'Label':>5}  {'Collected':>10}  {'Target':>8}")
    print("─" * 60)
    incomplete = []
    for bravais_id in range(N_CLASSES):
        n = counts[bravais_id]
        flag = "✓" if n >= n_per_class else "✗ INCOMPLETE"
        print(f"{CLASS_NAMES[bravais_id]:>10}  {bravais_id:>5}  {n:>10}  "
              f"{n_per_class:>8}  {flag}")
        if n < n_per_class:
            incomplete.append(CLASS_NAMES[bravais_id])
    print("─" * 60)
    if incomplete:
        warnings.warn(
            f"These classes had fewer than {n_per_class} samples in the "
            f"downloaded shards: {incomplete}. "
            "Increase the number of shards or reduce n_per_class.",
            RuntimeWarning,
            stacklevel=2,
        )

    # ── Assemble final arrays ─────────────────────────────────────────────
    X_list, y_list = [], []
    for bravais_id in range(N_CLASSES):
        samples = buckets[bravais_id][:n_per_class]   # cap at n_per_class
        X_list.extend(samples)
        y_list.extend([bravais_id] * len(samples))

    X = np.stack(X_list, axis=0).astype(np.float32)   # (N, 1024)
    y = np.array(y_list,           dtype=np.int32)     # (N,)

    # Shuffle
    perm = np.random.default_rng(seed=42).permutation(len(X))
    X, y = X[perm], y[perm]

    return X, y


# ===========================================================================
# SECTION 6  —  Disk I/O
# ===========================================================================

def save_npz(X: np.ndarray, y: np.ndarray, output_path: str) -> None:
    """Save dataset as a compressed NumPy .npz file."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    np.savez_compressed(
        output_path,
        X            = X,
        y            = y,
        class_names  = np.array(CLASS_NAMES),
        Q_axis       = Q_AXIS,
        source       = np.array("SimXRD-4M (caobin/SimXRD, Hugging Face)"),
    )
    size_mb = os.path.getsize(output_path + ".npz") / 1e6
    print(f"[data_loader] Saved → {output_path}.npz  "
          f"({size_mb:.1f} MB)")


def save_h5(X: np.ndarray, y: np.ndarray, output_path: str) -> None:
    """Save dataset as an HDF5 file (faster random access during training)."""
    if not H5PY_AVAILABLE:
        raise RuntimeError("h5py not installed. Run: pip install h5py")
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with h5py.File(output_path, "w") as f:
        f.create_dataset("X",           data=X,                     compression="gzip")
        f.create_dataset("y",           data=y,                     compression="gzip")
        f.create_dataset("Q_axis",      data=Q_AXIS)
        f.create_dataset("class_names", data=np.array(CLASS_NAMES, dtype="S"))
        f.attrs["source"] = "SimXRD-4M (caobin/SimXRD, Hugging Face)"
        f.attrs["n_bins"] = N_BINS
        f.attrs["Q_min"]  = Q_MIN
        f.attrs["Q_max"]  = Q_MAX
    size_mb = os.path.getsize(output_path) / 1e6
    print(f"[data_loader] Saved → {output_path}  ({size_mb:.1f} MB)")


# ===========================================================================
# SECTION 7  —  Main Pipeline
# ===========================================================================

def run(
    n_per_class:  int  = 5_000,
    output:       str  = "data/processed/simxrd_balanced",
    fmt:          str  = "npz",
    db_dir:       str  = "data/simxrd_shards",
    no_download:  bool = False,
    max_shards:   int  = -1,
) -> None:
    """
    Full end-to-end pipeline:
      1. (Optional) list & download .db shards from Hugging Face.
      2. Stream through shards to collect balanced samples.
      3. Save to disk.

    Parameters
    ----------
    n_per_class  : samples to collect per Bravais class (default 5 000)
    output       : output path (without extension)
    fmt          : 'npz' or 'h5'
    db_dir       : local directory for .db shard files
    no_download  : if True, use already-downloaded files in db_dir
    max_shards   : limit shard downloads (useful for quick tests). -1 = all
    """
    print("=" * 60)
    print("  DeepBravais — SimXRD-4M Data Loader")
    print("=" * 60)
    print(f"  Target : {n_per_class} samples × {N_CLASSES} classes "
          f"= {n_per_class * N_CLASSES:,} total")
    print(f"  Format : {fmt.upper()}")
    print(f"  Output : {output}.{fmt}")
    print("=" * 60 + "\n")

    os.makedirs(db_dir, exist_ok=True)
    db_paths: List[str] = []

    # ── Step 1: Discover / download shards ───────────────────────────────
    if no_download:
        # Use whatever .db files are already on disk
        db_paths = sorted(Path(db_dir).rglob("*.db"))
        if not db_paths:
            sys.exit(
                f"[data_loader] ERROR: --no_download set but no .db files "
                f"found in {db_dir!r}. "
                "Remove --no_download or pre-populate the directory."
            )
        print(f"[data_loader] Found {len(db_paths)} local shard(s) in {db_dir!r}.")
    else:
        print("[data_loader] Querying Hugging Face for shard list …")
        remote_files = _list_db_files()
        if max_shards > 0:
            remote_files = remote_files[:max_shards]
        print(f"[data_loader] Found {len(remote_files)} shard(s). "
              "Downloading (cached if already present) …\n")

        for repo_file in tqdm(remote_files, desc="Downloading shards", unit="shard"):
            local_path = _download_shard(repo_file, local_dir=db_dir)
            db_paths.append(local_path)

        print(f"\n[data_loader] {len(db_paths)} shard(s) ready in {db_dir!r}.\n")

    if not db_paths:
        sys.exit("[data_loader] No .db files available. Aborting.")

    # ── Step 2: Collect balanced samples ─────────────────────────────────
    print("[data_loader] Streaming shards for stratified sampling …\n")
    X, y = collect_balanced_samples(
        db_paths    = [str(p) for p in db_paths],
        n_per_class = n_per_class,
    )

    print(f"\n[data_loader] Final dataset: X={X.shape}  y={y.shape}")

    # ── Step 3: Save ──────────────────────────────────────────────────────
    if fmt == "h5":
        save_h5(X, y, output + ".h5")
    else:
        # savez_compressed adds .npz automatically
        save_npz(X, y, output)

    print("\n[data_loader] Done ✓")
    print(f"  Load with: data = np.load('{output}.{fmt}')")


# ===========================================================================
# SECTION 8  —  CLI
# ===========================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Download the SimXRD-4M dataset from Hugging Face and produce a "
            "balanced PXRD dataset for DeepBravais training."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--n_per_class", type=int, default=5_000,
        help="Number of samples to collect per Bravais class.",
    )
    parser.add_argument(
        "--output", type=str, default="data/processed/simxrd_balanced",
        help="Output path (without file extension).",
    )
    parser.add_argument(
        "--format", dest="fmt", choices=["npz", "h5"], default="npz",
        help="Output format: 'npz' (numpy compressed) or 'h5' (HDF5).",
    )
    parser.add_argument(
        "--db_dir", type=str, default="data/simxrd_shards",
        help="Local directory to cache downloaded .db shards.",
    )
    parser.add_argument(
        "--no_download", action="store_true",
        help="Skip downloading; use .db files already present in --db_dir.",
    )
    parser.add_argument(
        "--max_shards", type=int, default=-1,
        help="Limit the number of shards to download (-1 = all). "
             "Useful for quick tests on Kaggle.",
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Global random seed.",
    )

    args = parser.parse_args()
    np.random.seed(args.seed)

    run(
        n_per_class = args.n_per_class,
        output      = args.output,
        fmt         = args.fmt,
        db_dir      = args.db_dir,
        no_download = args.no_download,
        max_shards  = args.max_shards,
    )
